### ISSUE TITLE
help: about draw text

### ISSUE THREAD

**Issue by llcat** [vagran/dxf-viewer-example-src#1]
if i need draw text, i must offer a xxx.ttf file？my language is zh-Hans, it's means i have to load a large size ttf file, any suggestion or best practices?
https://github.com/vagran/dxf-viewer-example-src/blob/0b16e6fa5365b4896e0c03e26ed428fa27b4b91c/src/components/ViewerPage.vue#L17-L19

**Comment by vagran** [comment]
Yes, you need to provide a font which contains your language. If you are afraid of large font file (which may be a case for some universal multi-language font) you should find a font file which contains only the required language.
By the way, Noto font in this example was meant to be such multilingual font. Is it able to display your language?

P.S. Sory for late reply, the notification was lost in junk folder.

**Comment by llcat** [comment]
thanks for reply, the font file in demo can't cover all character in my language, i replace an other font file is ok, but a litte big, so get the glyph by content from server may be a better choice for me, hah~ hope dxf-viewer will support  more features like mtext, hatch and so on !
