### ISSUE TITLE
Unsupported OpenType signature

### ISSUE THREAD

**Issue by cmastelaro** [vagran/dxf-viewer-example-src#10]
I don't know what i'm doing wrong !

I'm getting this error trying to render a dxf file.

```
Error: Unsupported OpenType signature <htm DxfViewerWorker.4542b64f.worker.js:7:647698
    _ProcessRequest https://dev.geoofficepro.com.br/js/DxfViewerWorker.4542b64f.worker.js:7
    r https://dev.geoofficepro.com.br/js/DxfViewerWorker.4542b64f.worker.js:16
    l https://dev.geoofficepro.com.br/js/DxfViewerWorker.4542b64f.worker.js:16
```
but, before this error above i've got 

```
GET https://dev.geoofficepro.com.br/js/fonts/Roboto-LightItalic.2eeb30eb.ttf
[HTTP/1.1 404 Not Found 9ms]

```
i'm missing something that i can't figure out  !

any help , any thoughts will be appreciate, thanks

**Comment by arlebedev** [comment]
Seems like you don't have font files available in your deployment.

**Comment by cmastelaro** [comment]
Yeah ! you are absolutely right !! 

thanks again !! see ya
