### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by kikyoluka** [vagran/dxf-viewer-example-src#5]
Hello, thank you very much for your example. I am a beginner for dxf. I have this error after porting the example in exaxple to my project. Is there any solution?
```
Failed to compile.

./node_modules/dxf-viewer/src/DxfViewer.js 848:105
Module parse failed: Unexpected token (848:105)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|     const materialFactory = this.key.geometryType === BatchingKey.GeometryType.POINTS || this.key.geometryType === BatchingKey.GeometryType.POINT_INSTANCE ? this.viewer._GetSimplePointMaterial : this.viewer._GetSimpleColorMaterial;
>     const material = materialFactory.call(this.viewer, this.viewer._TransformColor(color), instanceBatch?.GetInstanceType() ?? InstanceType.NONE);
|     let objConstructor;
| 
```

**Comment by vagran** [comment]
Probably you need something similar to this option in Vue configuration:
https://github.com/vagran/dxf-viewer-example-src/blob/0b16e6fa5365b4896e0c03e26ed428fa27b4b91c/vue.config.js#L5

**Comment by kikyoluka** [comment]
> 您可能需要类似此选项的Vue配置：
> https://github.com/vagran/dxf-viewer-example-src/blob/0b16e6fa5365b4896e0c03e26ed428fa27b4b91c/vue.config.js#L5

Thanks for your answer. 
I set it up and Include babel.config.js as per your, but it still prompts the above error.
I think it may be an error caused by ?. and ?? in the es2020 specification. So I can only reduce the version of part of es2020 in the code file.
There is another question, is there any way to get the graphics data of the canvas in `this.$refs.canvasContainer`,
I use the `HTMLCanvasElement.toDataURL()` method to get the data of the canvas, but I can only get a black box, not the dxf data inside.

**Comment by vagran** [comment]
If you don't use `vue.config.js`, it may have different syntax, e.g. `babel.config.js` may have something like `exclude: /node_modules\/(?!dxf-viewer)/`.
Canvas reference can be obtained by `this.dxfViewer.canvas`. I am not really sure why you get black contents. May be you call `toDataURL()` before the image is rendered first time?

**Comment by kikyoluka** [comment]
> If you don't use , it may have different syntax, e.g. may have something like .
> Canvas reference can be obtained by . I am not really sure why you get black contents. May be you call before the image is rendered first time?`vue.config.js``babel.config.js``exclude: /node_modules\/(?!dxf-viewer)/``this.dxfViewer.canvas``toDataURL()`

I use your example-src project and changed the event of the dxf-viewer on GitHub button . 
After the dxf file is imported for rendering,I click the button to get it. But the final rendering to the body is just a black frame. 
Maybe there is a problem with my code ?
![image](https://user-images.githubusercontent.com/35128837/127764661-21f65220-74f0-489f-8b3a-b4aa9f349e3d.png)
![image](https://user-images.githubusercontent.com/35128837/127764715-cbe7d525-0404-4d5a-8a0a-28ec07c4b8fd.png)

**Comment by vagran** [comment]
Might be CORS issue. You should always check your browser console for errors and warnings when experimenting with web-app code.
