### ISSUE TITLE
I cant run

### ISSUE THREAD

**Issue by flyingmouse0** [vagran/dxf-viewer-example-src#6]
Hello, I am quite a novice. I follow the commands but I can't run them. What should I do? sorry for taking your time
![1](https://user-images.githubusercontent.com/87943151/130721452-0fd90c07-f634-402e-bd91-443c88df11f6.png)
![2](https://user-images.githubusercontent.com/87943151/130721462-b6ba3139-f3de-47ac-b754-b5fc86965757.png)

**Comment by flyingmouse0** [comment]
> Seems you did not run `npm install` first.

Hello, thank you for your answer. 
Things I did:

1. I download the file and open the folder it is in with visual studio code.
2. i open terminal in folder
3. "npm install"
4. "npm run build"
5. "cd public"
6. "npm install"
7. and I close the terminal
8. I run windows live server and the result is:
![image](https://user-images.githubusercontent.com/87943151/131204521-51f65703-5148-42df-9732-516a0396607f.png)

**Comment by flyingmouse0** [comment]
i just want to make it executable and i am very newbie.

**Comment by vagran** [comment]
The simplest way is mentioned in README - just run `npm run serve` after `npm install`. It will run node.js built-in HTTP server. If you want to run it standalone, you just need to serve `dist` directory content by some HTTP server. The `dist` directory is created by `npm run build`. As I see from your screenshot, you are trying to serve `public` directory content which is wrong. This is directory with source files, not build product.
